#!/usr/bin/env python3
## 308
## File description:
## reedpipes
##

import sys
import csv
from math import *
#from numpy import *

R = [0, 0, 0, 0, 0]
N = 0
V = [0.0, 0.0, 0.0, 0.0, 0.0]

def help():
    if len(sys.argv) == 2:
        if sys.argv[1] == "-h" or sys.argv[1] == "--help":
            print("USAGE")
            print("\t./308reedpipes r0 r5 r10 r15 r20 n\n")
            print("DESCRIPTION")
            print("\tr0\tradius (in cm) of pipe at the 0cm abscissa")
            print("\tr5\tradius (in cm) of pipe at the 5cm abscissa")
            print("\tr10\tradius (in cm) of pipe at the 10cm abscissa")
            print("\tr15\tradius (in cm) of pipe at the 15cm abscissa")
            print("\tr20\tradius (in cm) of pipe at the 20cm abscissa")
            print("\tn\tnumber of points needed to display the radius")
            exit(0)

def rigor():
    global R
    global N
    if len(sys.argv) != 7:
        exit(84)
    try:
        r0 = float(sys.argv[1])
        r5 = float(sys.argv[2])
        r10 = float(sys.argv[3])
        r15 = float(sys.argv[4])
        r20 = float(sys.argv[5])
        N = int(sys.argv[6])
    except:
        exit(84)
    if r0 > r20:
        exit(84)
    if r0 <= 0 or r5 <= 0 or r10 <= 0 or r15 <= 0 or r20 <= 0 or N <= 0:
        exit(84)
    R = [r0, r5, r10, r15, r20]


def splines():
    i = 1
    A = 6 * (R[2] - 2 * R[1] + R[0]) / 50
    B = 6 * (R[3] - 2 * R[2] + R[1]) / 50
    C = 6 * (R[4] - 2 * R[3] + R[2]) / 50
    V[2] = (B - (A + C) / 4) * 4 / 7
    V[1] = A / 2 - 0.25 * V[2]
    V[3] = C / 2 - 0.25 * V[2]

def calc(i, X, x):
    return (- V[i - 1] / 30 * pow(X - x[i], 3)
                + V[i] / 30 * pow(X - x[i - 1], 3)
                - (R[i - 1] / 5 - 5 / 6 * V[i - 1])
                * (X - x[i])
                + (R[i] / 5 - 5 / 6 * V[i])
                * (X - x[i - 1]))

def calculate():
    x = [0, 5, 10, 15, 20]
    res = []
    for d in range(N):
        X = 20 / (N - 1) * d
        i = int((X - 0.01) / 5) + 1
        result = calc(i, X, x)
        res.append(result)
    return res

def reedpipes():
    splines()
    res = calculate()
    if round(V[1], 1) == -0.0:
        V[1] = 0.0
    if round(V[2], 1) == -0.0:
        V[2] = 0.0
    if round(V[3], 1) == -0.0:
        V[3] = 0.0
    print("vector result: [%.1f, %.1f, %.1f, %.1f, %.1f]" %(V[0], V[1], V[2], V[3], V[4]))
    for i in range(0, N):
        print("abscissa: %.1f cm\tradius: %.1f cm" %((20/(N-1)*i), res[i]))

def main():
    help()
    rigor()
    reedpipes()

if __name__ == "__main__":
    main()
